var germanTranslation = {
  "home": "Home",
  "about": "Über uns",
  "navbarDropdown":"Sprache",
  "english":"Englisch",
  "german":"Deutsch",
  "welcomeHeading": "Willkommen bei Add.ToMap!",
  "welcomeDescription":"Willkommenstext und Beschreibung",
  "processStepsHeading":"Digitalisierungs- und Kartierungsschritte",
  "uploadTab":"1 Hochladen",
  "verifyDigTab":"2 Digitalisierung",
  "verifyGeoTab":"3 Geokodierung",
  "chooseFile":"Wählen Sie ein Foto mit Adressen",
  "NextToTesseract":"Weiter",
  "NextToPhoton":"Weiter",
  "NextToMap":"Weiter",
  "digitDescription":"Wählen und korrigieren Sie alle Adressen, welche geokodiert werden und in der Karte abgebildet werden sollen. Die einzelnen Adressenkomponenten sollten durch ein Komma voneinander getrennt werden.",
  "geocDescription":"Wählen Sie alle Adressen aus, welche auf der Karte dargestellt werden sollen.",
  "cancel1":"Abbrechen",
  "cancel2":"Abbrechen",
  "mapHeading":"Kartierte Adressen"
}
