var englishTranslation = {
  "home": "Home",
  "about": "About",
  "navbarDropdown":"Language",
  "english":"English",
  "german":"German",
  "welcomeHeading":"Welcome to Add.ToMap!",
  "welcomeDescription":"This website converts your photo of one or more addresses into a point on a map. Please follow the steps below.",
  "processStepsHeading":"Digitalization and mapping steps",
  "uploadTab":"1 Upload",
  "verifyDigTab":"2 Digitalization",
  "verifyGeoTab":"3 Geocoding",
  "chooseFile":"Choose an image of addresses",
  "NextToTesseract":"Next",
  "NextToPhoton":"Next",
  "NextToMap":"Next",
  "digitDescription":"Please select and correct all addresses, which should be geocoded and shown on the map. Each part of the address should be separated by a comma.",
  "geocDescription":"Please select all addresses, which should be shown on the map.",
  "cancel1":"Cancel",
  "cancel2":"Cancel",
  "mapHeading":"Mapped addresses",
  "errorTitle":"Oops, something went wrong!",
  "load": "loading ...",
  "description": "Description",
  "who": "Who?",
  "whoT" : "This project was created by Melanie Riester, Tibebu Galaso and Nina Kirschner in Wintersemester 2019 / 2020 in the study course Open Source GIS and the study program Geomatics at the University of Applied Science in Karlsruhe.",
  "what": "What?",
  "whatT" : "The task was to implement a self-chosen open-source project, which includes the fields of Open Source, Web and GIS. The result is the project Add.2Map (abbreviation for 'Address to map' or 'Add point to map'). The purpose of this project is to upload a photo with one or more addresses and to get the position of these address(es) on a map as a result. This makes sense especially when several analogue addresses are involved, as digitalization is automated and time can be saved. It is recommended to use the webpage Add.2Map from a mobile device as a photo of addresses can be taken directly.",
  "hList": "What happened if I don't get a result or not the result that I expected?",
  "uhList": "That could have many different reasons:",
  "li1":"Image size is too small",
  "li2":"Image quality is too low (try to cut the addresses out and increase contrast)",
  "li3":"Address(es) does not exist or the Geocoder couldn't find them",
  "li4":"If the address is shown on the map in a wrong position, it might be that to less information was given",
  "li5":"If the internet connection is too bad, the image recognition takes to long and stops after 30 seconds",
  "osT": "Used open-source tools",
  "relaodPageButton": "Reset page"
}
