var englishTranslation = {
  "home": "Home",
  "about": "About",
  "navbarDropdown":"Language",
  "english":"English",
  "german":"German",
  "welcomeHeading":"Welcome to Add.ToMap!",
  "welcomeDescription":"This website converts your photo of one or more addresses into a point on a map. Please follow the steps below.",
  "processStepsHeading":"Digitalization and mapping steps",
  "uploadTab":"1 Upload",
  "verifyDigTab":"2 Digitalization",
  "verifyGeoTab":"3 Geocoding",
  "chooseFile":"Choose an image of addresses",
  "NextToTesseract":"Next",
  "NextToPhoton":"Next",
  "NextToMap":"Next",
  "digitDescription":"Please select and correct all addresses, which should be geocoded and shown on the map. Each part of the address should be separated by a comma.",
  "geocDescription":"Please select all addresses, which should be shown on the map.",
  "cancel1":"Cancel",
  "cancel2":"Cancel",
  "mapHeading":"Mapped addresses"
}
