var englishTranslation = {
  "home": "Home",
  "about": "About",
  "navbarDropdown":"Language",
  "english":"English",
  "german":"German",
  "welcomeHeading":"Welcome to Add.ToMap!",
  "welcomeDescription":"This website converts your photo of one or more addresses into a point on a map. Please follow the steps below.",
  "processStepsHeading":"Digitalization and mapping steps",
  "uploadTab":"1 Upload",
  "verifyDigTab":"2 Digitalization",
  "verifyGeoTab":"3 Geocoding",
  "chooseFile":"Choose an image of addresses",
  "NextToTesseract":"Next",
  "NextToPhoton":"Next",
  "NextToMap":"Next",
  "digitDescription":"Please select and correct all addresses, which should be geocoded and shown on the map. Each part of the address should be separated by a comma.",
  "geocDescription":"Please select all addresses, which should be shown on the map.",
  "cancel1":"Cancel",
  "cancel2":"Cancel",
  "mapHeading":"Mapped addresses",
  "errorTitle":"Oops, something went wrong!",
  "load": "loading ...",
  "description": "Description",
  "who": "Who?",
  "whoT" : "This project was created by Melanie Riester, Tibebu Galaso and Nina Kirschner in Wintersemester 2019 / 2020 in the study course Open Source GIS and the study program Geomatics at the university of applied science in Karlsruhe. The task was to do a project which is built on open source programs or libaries.",
  "what": "What?",
  "whatT" : "The result is this website: Add.2Map. This Website is responive. The purpose is to upload a picture with one ore more addresses and to get the position of this address(es) on a map.",
  "hList": "What happend if i don't get a result or not the result that i expected?",
  "uhList": "That could have many different reasons:",
  "li1":"Image size is too small",
  "li2":"Image quality is too low (try to cut the addresses out and increase contrast)",
  "li3":"Adress(es) does not exists or the Geocoder couldn't find them",
  "li4":"If the address is at a wrong position, it might be that to less information was given",
  "osT": "Used open-source tools",
  "relaodPageButton": "Reset page"
}
